# A pipeline for triggering the Cucumber Feature Files
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: gem install bundler:1.16.4
  displayName: 'bundle install'


- script: gem install rails && rails -v
  displayName: 'gem install rails'

- script: gem install cucumber
  displayName: 'Installing Cucumber'

- script: cucumber features/google.feature -f pretty -f html -o features/CucumberOutput.html
  displayName: 'Executing TCs'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '47e7e088-d4f9-4c3b-9006-0e6af0cde64a'
    definition: '3'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    allowPartiallySucceededBuilds: true
    allowFailedBuilds: true
    itemPattern: '**.html'
    targetPath: 'features'

- script: ls -ltr /home/vsts/work/1/s/features/CucumberOutput.html
  displayName: 'Checking the Artifact'
    
   

- script: cucumber features/google.feature -f pretty -f html -o $(Build.ArtifactStagingDirectory)/CucumberOutput.html
  displayName: 'Executing TCs 1'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'CucumberOutput.html'
    publishLocation: 'Container'

- script: ls -ltr $(Build.ArtifactStagingDirectory)/CucumberOutput.html
  displayName: 'Checking the Artifacts'