# A pipeline for triggering the Cucumber Feature Files
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: gem install bundler:1.16.4
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'


- script: gem install rails && rails -v
  displayName: 'gem install rails'
