# A pipeline for triggering the Cucumber Feature Files
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: gem install bundler:1.16.4
  displayName: 'bundle install'


- script: gem install rails && rails -v
  displayName: 'gem install rails'

- script: gem install cucumber
  displayName: 'Installing Cucumber'

- script: cucumber features/google.feature -f pretty -f html -o index.html
  displayName: 'Executing TCs'
